// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SMART_EVENT_MANAGEMENT_SYSTEM.Data;

#nullable disable

namespace SMART_EVENT_MANAGEMENT_SYSTEM.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260918170813_Initi")]
    partial class Initi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SMART_EVENT_MANAGEMENT_SYSTEM.Models.Attendee", b =>
                {
                    b.Property<int>("AttendeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendeeId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AttendeeId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Attendees");

                    b.HasData(
                        new
                        {
                            AttendeeId = 1,
                            Email = "mai.mohamed@example.com",
                            FullName = "Mai Mohamed",
                            Phone = "+201000111222"
                        },
                        new
                        {
                            AttendeeId = 2,
                            Email = "youssef.ahmed@example.com",
                            FullName = "Youssef Ahmed",
                            Phone = "+201011222333"
                        },
                        new
                        {
                            AttendeeId = 3,
                            Email = "mariam.khaled@example.com",
                            FullName = "Mariam Khaled",
                            Phone = "+201022333444"
                        },
                        new
                        {
                            AttendeeId = 4,
                            Email = "karim.mostafa@example.com",
                            FullName = "Karim Mostafa",
                            Phone = "+201033444555"
                        },
                        new
                        {
                            AttendeeId = 5,
                            Email = "lina.omar@example.com",
                            FullName = "Lina Omar",
                            Phone = "+201044555666"
                        },
                        new
                        {
                            AttendeeId = 6,
                            Email = "adam.hassan@example.com",
                            FullName = "Adam Hassan",
                            Phone = "+201055666777"
                        });
                });

            modelBuilder.Entity("SMART_EVENT_MANAGEMENT_SYSTEM.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrganizerId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("EventId");

                    b.HasIndex("OrganizerId");

                    b.HasIndex("VenueId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            Capacity = 3000,
                            Category = "Technology",
                            Description = "A conference about technology and innovation.",
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            EventDate = new DateTime(2026, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrganizerId = 1,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "Tech Innovation Summit",
                            VenueId = 1
                        },
                        new
                        {
                            EventId = 2,
                            Capacity = 1500,
                            Category = "Business",
                            Description = "A forum for young business leaders.",
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            EventDate = new DateTime(2026, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrganizerId = 2,
                            StartTime = new TimeSpan(0, 11, 0, 0, 0),
                            Title = "Business Leadership Forum",
                            VenueId = 2
                        },
                        new
                        {
                            EventId = 3,
                            Capacity = 500,
                            Category = "Marketing",
                            Description = "A practical workshop about digital marketing.",
                            EndTime = new TimeSpan(0, 14, 0, 0, 0),
                            EventDate = new DateTime(2026, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrganizerId = 3,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0),
                            Title = "Digital Marketing Workshop",
                            VenueId = 3
                        },
                        new
                        {
                            EventId = 4,
                            Capacity = 2000,
                            Category = "Technology",
                            Description = "Exploring artificial intelligence and future technologies.",
                            EndTime = new TimeSpan(0, 15, 0, 0, 0),
                            EventDate = new DateTime(2026, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrganizerId = 1,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "AI and Future Technologies",
                            VenueId = 2
                        },
                        new
                        {
                            EventId = 5,
                            Capacity = 800,
                            Category = "Entrepreneurship",
                            Description = "An event connecting entrepreneurs and startups.",
                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
                            EventDate = new DateTime(2026, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrganizerId = 2,
                            StartTime = new TimeSpan(0, 12, 0, 0, 0),
                            Title = "Entrepreneurship Meetup",
                            VenueId = 1
                        });
                });

            modelBuilder.Entity("SMART_EVENT_MANAGEMENT_SYSTEM.Models.Organizer", b =>
                {
                    b.Property<int>("OrganizerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrganizerId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrganizerId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Organizers");

                    b.HasData(
                        new
                        {
                            OrganizerId = 1,
                            Email = "ahmed.hassan@example.com",
                            FullName = "Ahmed Hassan",
                            Phone = "+201001234567"
                        },
                        new
                        {
                            OrganizerId = 2,
                            Email = "sara.mohamed@example.com",
                            FullName = "Sara Mohamed",
                            Phone = "+201112345678"
                        },
                        new
                        {
                            OrganizerId = 3,
                            Email = "omar.ali@example.com",
                            FullName = "Omar Ali",
                            Phone = "+201223456789"
                        });
                });

            modelBuilder.Entity("SMART_EVENT_MANAGEMENT_SYSTEM.Models.Registration", b =>
                {
                    b.Property<int>("RegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistrationId"));

                    b.Property<int>("AttendeeId")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("RegistrationId");

                    b.HasIndex("AttendeeId");

                    b.HasIndex("EventId", "AttendeeId")
                        .IsUnique();

                    b.ToTable("Registrations");

                    b.HasData(
                        new
                        {
                            RegistrationId = 1,
                            AttendeeId = 1,
                            EventId = 1,
                            RegistrationDate = new DateTime(2026, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Confirmed"
                        },
                        new
                        {
                            RegistrationId = 2,
                            AttendeeId = 2,
                            EventId = 1,
                            RegistrationDate = new DateTime(2026, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Confirmed"
                        },
                        new
                        {
                            RegistrationId = 3,
                            AttendeeId = 3,
                            EventId = 2,
                            RegistrationDate = new DateTime(2026, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending"
                        },
                        new
                        {
                            RegistrationId = 4,
                            AttendeeId = 4,
                            EventId = 2,
                            RegistrationDate = new DateTime(2026, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Confirmed"
                        },
                        new
                        {
                            RegistrationId = 5,
                            AttendeeId = 1,
                            EventId = 3,
                            RegistrationDate = new DateTime(2026, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Confirmed"
                        },
                        new
                        {
                            RegistrationId = 6,
                            AttendeeId = 5,
                            EventId = 4,
                            RegistrationDate = new DateTime(2026, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Cancelled"
                        },
                        new
                        {
                            RegistrationId = 7,
                            AttendeeId = 6,
                            EventId = 5,
                            RegistrationDate = new DateTime(2026, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Confirmed"
                        },
                        new
                        {
                            RegistrationId = 8,
                            AttendeeId = 3,
                            EventId = 4,
                            RegistrationDate = new DateTime(2026, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending"
                        });
                });

            modelBuilder.Entity("SMART_EVENT_MANAGEMENT_SYSTEM.Models.Venue", b =>
                {
                    b.Property<int>("VenueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VenueId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("VenueId");

                    b.ToTable("Venues");

                    b.HasData(
                        new
                        {
                            VenueId = 1,
                            Capacity = 5000,
                            Location = "Nasr City, Cairo",
                            Name = "Cairo Convention Center"
                        },
                        new
                        {
                            VenueId = 2,
                            Capacity = 2500,
                            Location = "Alexandria, Egypt",
                            Name = "Alexandria Cultural Hall"
                        },
                        new
                        {
                            VenueId = 3,
                            Capacity = 1000,
                            Location = "Maadi, Cairo",
                            Name = "Nile Conference Hall"
                        });
                });

            modelBuilder.Entity("SMART_EVENT_MANAGEMENT_SYSTEM.Models.Event", b =>
                {
                    b.HasOne("SMART_EVENT_MANAGEMENT_SYSTEM.Models.Organizer", "Organizer")
                        .WithMany("Events")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMART_EVENT_MANAGEMENT_SYSTEM.Models.Venue", "Venue")
                        .WithMany("Events")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizer");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("SMART_EVENT_MANAGEMENT_SYSTEM.Models.Registration", b =>
                {
                    b.HasOne("SMART_EVENT_MANAGEMENT_SYSTEM.Models.Attendee", "Attendee")
                        .WithMany("Registrations")
                        .HasForeignKey("AttendeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMART_EVENT_MANAGEMENT_SYSTEM.Models.Event", "Event")
                        .WithMany("Registrations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attendee");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("SMART_EVENT_MANAGEMENT_SYSTEM.Models.Attendee", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("SMART_EVENT_MANAGEMENT_SYSTEM.Models.Event", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("SMART_EVENT_MANAGEMENT_SYSTEM.Models.Organizer", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("SMART_EVENT_MANAGEMENT_SYSTEM.Models.Venue", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
